import { ITag, IJob } from "../interfaces";

export const dummyUser = {
    id: 1,
    first_name: "Kshitiz",
    last_name: "Gupta",
    date_joined: new Date(),
    role: "HR",
    gender: "Male",
    email: "kshitizgupta@gmail.com"
};

export const dummyTags: ITag[] = [
    {
        id: 1,
        name: "Web Development"
    },
    {
        id: 2,
        name: "Android Development"
    },
    {
        id: 3,
        name: "Automation Testing"
    },
    {
        id: 4,
        name: 'Playwright'
    },
    {
        id: 5,
        name: 'Backend Development'
    },
    {
        id: 6,
        name: 'Cloud Computing'
    },
    {
        id: 7,
        name: 'Microservices'
    }
]

// var dummyApplicant: IApplicant = {
//     id: 1,
//     job_id: 1,
//     applied_user: dummyUser,
//     job: jobsList[0],
//     status: "In Progress",
//     comment: "Needs more work in web design",
//     created_at: new Date(),
// }

export const jobsList: IJob[] = [
    {
        id: 1,
        title: "Senior Software Developer",
        description: "Software Developer Required for TSM",
        location: "Gurgaon",
        type: "1",
        category: "Angular, Nodejs",
        last_date: new Date(),
        company_name: "Keysight Technologies",
        company_description: "Hardware Manufacturing, Cloud Computing",
        website: "www.keysight.com",
        created_at: new Date(),
        filled: false,
        salary: 300000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[0]],
        total_candidates: 100,
    },
    {
        id: 2,
        title: "Android Developer",
        description: "Need Android Developer for new team at HCL Technologies",
        location: "Bangaluru",
        type: "1",
        category: "Android, Java, Kotlin",
        last_date: new Date(),
        company_name: "HCL Technologies",
        company_description: "Personal Computing",
        website: "www.hcl.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[1]],
        total_candidates: 100,
    },
    {
        id: 3,
        title: "Senior Developer - React",
        description: "Microsoft is leading solutions provider for OS and cloud solutions",
        location: "Hyderabad",
        type: "1",
        category: "React, JavaScript, Jest",
        last_date: new Date(),
        company_name: "Microsoft",
        company_description: "Personal Computing",
        website: "www.microsoft.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[0]],
        total_candidates: 100,
    },
    {
        id: 4,
        title: "Playright Developer",
        description: "Automation Testing is the backbone of robust software delovery.",
        location: "Noida",
        type: "1",
        category: "Automation Testing, Playwright",
        last_date: new Date(),
        company_name: "Keysight Technologies",
        company_description: "Hardware Manufacturing, Cloud Computing",
        website: "www.keysight.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[2], dummyTags[3]],
        total_candidates: 100,
    },
    {
        id: 5,
        title: "Senior Developer - Nodejs",
        description: "Microsoft is leading solutions provider for OS and cloud solutions",
        location: "Hyderabad",
        type: "1",
        category: "Nodejs, JavaScript",
        last_date: new Date(),
        company_name: "Microsoft",
        company_description: "Personal Computing",
        website: "www.microsoft.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[4]],
        total_candidates: 100,
    },
    {
        id: 6,
        title: "Cloud Solutions Architect",
        description: "Need an architect for our new Cloud Solutions team in Mumbai. The candidate needs to manage a team of 15 developers.",
        location: "Mumbai",
        type: "1",
        category: "Cloud Computing, Microservice Architecture",
        last_date: new Date(),
        company_name: "Lenovo",
        company_description: "Personal Computing, Hardware, Headsets, Laptops",
        website: "www.microsoft.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[5], dummyTags[6]],
        total_candidates: 100,
    },
    {
        id: 7,
        title: "R&D Engineer - Advanced",
        description: "Keysight is industry leader in hardware testing and manufacturing use cases. Our range of products include 5G, Electric Vehicles, and more",
        location: "Gurgaon",
        type: "1",
        category: ".Net Developer",
        last_date: new Date(),
        company_name: "Keysight",
        company_description: "Hardware Products, Cloud Computing",
        website: "www.keysight.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[4]],
        total_candidates: 100,
    },
    {
        id: 8,
        title: "Backend Developer - NodeJs",
        description: "one.com is a leading cloud solutions provider and has a range of products in the domain",
        location: "Gurgaon",
        type: "1",
        category: "NodeJs, JavaScript",
        last_date: new Date(),
        company_name: "one.com",
        company_description: "Cloud Hosting Solutions",
        website: "www.one.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[4]],
        total_candidates: 100,
    },
    {
        id: 9,
        title: "Senior Developer - Angular",
        description: "Microsoft is leading solutions provider for OS and cloud solutions",
        location: "Hyderabad",
        type: "2",
        category: "React, JavaScript, Jest",
        last_date: new Date(),
        company_name: "Microsoft",
        company_description: "Personal Computing",
        website: "www.microsoft.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[0]],
        total_candidates: 100,
    },
    {
        id: 10,
        title: "Intern Tech 1",
        description: "Google has the worlds best search engine and a host of cloud platform solutions for customers to easily deploy their applications",
        location: "Hyderabad",
        type: "3",
        category: "React, JavaScript, Jest",
        last_date: new Date(),
        company_name: "Google",
        company_description: "Personal Computing",
        website: "www.google.com",
        created_at: new Date(),
        filled: false,
        salary: 500000,
        tags: [1,2,4,5],
        user: dummyUser,
        applicant: undefined,
        job_tags: [dummyTags[0]],
        total_candidates: 100,
    },
]

export const loginUsers = [
    {
        email: "employee@google.com",
        password: "temp1234",
        role: "employee"
    },
    {
        email: "employer@google.com",
        password: "temp1234",
        role: "employer"
    }
]